### ISSUE TITLE
Keep compact style but (paradoxically) include titles?

### ISSUE THREAD

**Issue by gabrielastro** [keflavich/tex_compact_bib#4]
Hello,
This may again be more for @lmytime. Would it be possible to add the titles to the entries (articles, books, etc.), while otherwise keeping the same compact style? I would need this to fulfull a formal requirement of the bibliography for an application…
Thank you very much!
Gabriel

**Comment by lmytime** [comment]
Hi @gabrielastro, sorry for my late reply. I think you can directly add a `title` entry in the `FUNCTION {article}` as you want.
Hopefully, it is helpful.
<img width="632" alt="image" src="https://github.com/user-attachments/assets/bbdf1c42-ccc9-4918-961a-94f8a45481ed">

**Comment by gabrielastro** [comment]
Ah! That easy… Thank you! Sorry for not thinking of that. I ended up generating a new style with the `custom-bib` program and modifying it, using elements from yours. That worked well.
